# Generated by Django 5.2 on 2026-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
