# Generated by Django 5.2 on 2026-02-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Чем число меньше, тем выше в списке', verbose_name='Порядок сортировки'),
        ),
    ]
