# Generated by Django 5.2 on 2026-02-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_placeimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order']},
        ),
    ]
