# Generated by Django 5.2 on 2026-02-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order'], 'verbose_name': 'Фотография локации', 'verbose_name_plural': 'Фотографии локации'},
        ),
    ]
