# Generated by Django 5.2 on 2026-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_placeimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=300, verbose_name='Короткое описание'),
        ),
    ]
