# Generated by Django 5.2 on 2026-03-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='placeimage_order_index'),
        ),
    ]
