# Generated by Django 5.2 on 2026-03-07 06:59

from django.db import migrations


def fix_image_paths(apps, schema_editor):
    PlaceImage = apps.get_model('places', 'PlaceImage')
    
    updated = 0
    skipped = 0
    
    for img in PlaceImage.objects.all():
        old_path = img.image.name
        
        if old_path and old_path.startswith('static/'):
            new_path = old_path.replace('static/', '', 1)
            img.image.name = new_path
            img.save()
            updated += 1
        else:
            skipped += 1
    
    print(f"Миграция завершена. Обновлено: {updated}, пропущено: {skipped}")


def reverse_fix(apps, schema_editor):
    PlaceImage = apps.get_model('places', 'PlaceImage')
    
    for img in PlaceImage.objects.all():
        old_path = img.image.name
        
        if old_path and not old_path.startswith('static/') and old_path.startswith('images/'):
            new_path = 'static/' + old_path
            img.image.name = new_path
            img.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_placeimage_image'),
    ]

    operations = [
        migrations.RunPython(fix_image_paths, reverse_fix),
    ]
