# Generated by Django 5.2 on 2026-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_fix_image_paths_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(unique=True, verbose_name='Название'),
        ),
    ]
